name: healthify
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+23

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter # Add this line

  cupertino_icons: ^1.0.2

  intl: ^0.18.0

  sizer: ^2.0.15
  dotted_border: ^2.0.0+3

  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  internet_connection_checker: ^1.0.0+1
  dio: ^5.2.1+1
  shared_preferences: ^2.1.2
  fluttertoast: ^8.2.2
  flutter_local_notifications: ^14.1.1
  flutter_svg: ^2.0.5
  pin_code_fields: ^7.4.0
  carousel_slider: ^4.2.1
  country_pickers: ^2.0.0
  image_picker: ^1.0.0
  google_maps_flutter: ^2.3.0
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  url_launcher: ^6.1.12
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  firebase_auth: ^4.7.1
  firebase_crashlytics: ^3.4.8
  webview_flutter: ^4.2.2
  mobile_scanner: ^3.2.0
  dio_cache_interceptor_hive_store: ^3.2.1
  path_provider: ^2.1.0
  dio_cache_interceptor: ^3.4.2
  string_similarity: ^2.0.0

  flutter_rating_bar: ^4.0.1
  file_picker: ^5.3.1
  syncfusion_flutter_pdfviewer: ^22.2.9
  rename: ^3.0.1
  reve_chat_sdk: ^1.0.1
  share_plus: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appLogo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Alexandria
      fonts:
        - asset: assets/fonts/Alexandria-Black.ttf
        - asset: assets/fonts/Alexandria-Bold.ttf
        - asset: assets/fonts/Alexandria-ExtraBold.ttf
        - asset: assets/fonts/Alexandria-ExtraLight.ttf
        - asset: assets/fonts/Alexandria-Light.ttf
        - asset: assets/fonts/Alexandria-Medium.ttf
        - asset: assets/fonts/Alexandria-Regular.ttf
        - asset: assets/fonts/Alexandria-SemiBold.ttf
        - asset: assets/fonts/Alexandria-Thin.ttf
